-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 23:14:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `myecommerce` ;

-- -----------------------------------------------------
-- Table `myecommerce`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


myecommerce-- -----------------------------------------------------
-- Table `myecommerce`.`product_variations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`product_variations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(245) NULL DEFAULT NULL,
  `avaliable` INT NULL DEFAULT NULL,
  `variation_name` VARCHAR(245) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `price_from` FLOAT NULL DEFAULT NULL,
  `weight` INT NULL DEFAULT NULL,
  `order` INT NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_variations_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_variations_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `myecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecommerce`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `url` VARCHAR(245) NULL DEFAULT NULL,
  `order` INT NULL DEFAULT NULL,
  `product_variation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_images_product_variations1_idx` (`product_variation_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_images_product_variations1`
    FOREIGN KEY (`product_variation_id`)
    REFERENCES `myecommerce`.`product_variations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecommerce`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(245) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecommerce`.`categories_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`categories_products` (
  `categorie_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`categorie_id`, `product_id`),
  INDEX `fk_categories_has_products_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_categories_has_products_categories1_idx` (`categorie_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_has_products_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `myecommerce`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `myecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecommerce`.`banners_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`banners_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `banner_type` VARCHAR(245) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecommerce`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myecommerce`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL DEFAULT NULL,
  `url` VARCHAR(245) NULL DEFAULT NULL,
  `order` INT NULL DEFAULT NULL,
  `image_url` VARCHAR(245) NULL DEFAULT NULL,
  `banner_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_banner_banner_types1_idx` (`banner_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_banner_banner_types1`
    FOREIGN KEY (`banner_type_id`)
    REFERENCES `myecommerce`.`banners_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
myecommerce