const path = require('path')
const way = path.join(__dirname, 'subtitles')
const fn = require('./funcoes')

fn.readDirectory(way)
    .then(fn.getElementsWithEnd('.srt'))
    .then(fn.replaceValue('\\', '/'))   
    .then(fn.readFiles)
    .then(fn.arrayToString)
    .then(fn.splitStringsBy('\n'))
    .then(fn.deleteSpace)
    .then(fn.removeElementsIfIncludes('-->'))
    .then(fn.removeElementsIfIncludes('<b>'))
    .then(fn.removeElementsIfIncludes('www'))
    .then(fn.removeElementsIfContentNumbers)
    .then(fn.removeSimbols(fn.symbols))
    .then(fn.arrayToString)
    .then(fn.splitStringsBy(' '))    
    .then(fn.deleteSpace)
    .then(fn.removeElementsIfContentNumbers)
    .then(fn.accElements)    
    .then(fn.sortByAttr('qtd'))
    .then(console.log)
    .catch(console.log)

    
    