const express = require('express')
const app = express()  
const fn = require('./funcoes')

const path = require('path')
const way = path.join(__dirname, 'subtitles')

fn.readDirectory(way)
    .then(fn.getElementsWithEnd('.srt'))
    .then(fn.replaceValue('\\', '/'))   
    .then(fn.readFiles)
    .then(fn.arrayToString)
    .then(fn.splitStringsBy('\n'))
    .then(fn.deleteSpace)
    .then(fn.removeElementsIfIncludes('-->'))
    .then(fn.removeElementsIfIncludes('<b>'))
    .then(fn.removeElementsIfContentNumbers)
    .then(fn.removeSimbols(fn.symbols))
    .then(fn.arrayToString)
    .then(fn.splitStringsBy(' '))
    .then(fn.removeElementsIfContentNumbers)
    .then(fn.accElements)
    .then(console.log)
    .catch(console.log)